const languages = {
    'zh-TW': {
        home: '首頁',
        about: '關於我們',
        products: '產品目錄',
        contact: '聯絡我們',
        heroTitle: '專業摩托車零件製造商',
        heroSubtitle: '品質保證 · 價格實惠 · 專業服務',
        productsTitle: '產品目錄',
        cylinder: '汽缸',
        chain: '鏈條',
        clutch: '離合器',
        piston: '活塞',
        aboutTitle: '關於我們',
        aboutContent: '我們是台灣專業的摩托車零件製造商，專注於此領域超過30年。我們持續尋找優秀的合作夥伴，以擴展我們友善、專業、高效的服務。',
        contactTitle: '聯絡我們',
        companyName: '協皇企業有限公司',
        address: '地址：臺台中市南屯區黎明路一段533-2號',
        phone: '電話：0930 797 299',
        email: 'Email：bounerchang@gmail.com',
        copyright: '© 2024 協皇企業有限公司. All rights reserved.',
        productCategories: '產品分類',
        searchPlaceholder: '搜尋產品...',
        noProducts: '此類別暫無產品',
        noSearchResults: '找不到符合的產品',
        stock: '庫存',
        sold: '已售',
        originalPrice: '原價',
        currentPrice: '特價',
        inquiry: '詢價',
        specifications: '規格',
        model: '型號',
        currency: 'NT$',
        categoryNames: {
            cylinder: '汽缸系列',
            chain: '鏈條系列',
            clutch: '離合器系列',
            piston: '活塞系列',
            valve: '汽門系列',
            sprocket: '齒輪系列',
            brake: '煞車片系列',
            'oil-seal': '油封系列',
            cable: '線材系列'
        },
        categoryDescriptions: {
            cylinder: '高品質汽缸套件，適用於各種摩托車型號',
            chain: '專業傳動鏈條，確保最佳傳動效率',
            clutch: '耐用離合器組件，提供順暢的換檔體驗',
            piston: '精密活塞套件，確保引擎最佳性能',
            valve: '高精度汽門組件，確保引擎氣密性',
            sprocket: '耐磨齒輪，提供穩定的傳動效果',
            brake: '高性能煞車片，確保行車安全',
            'oil-seal': '優質油封，防止油料洩漏',
            cable: '耐用線材，確保操控靈敏度'
        },
        inquiryMessage: '即將為您詢價產品：',
        productName: '產品名稱',
        contactUs: '請聯繫我們',
        productNames: {
            '汽缸套件': '汽缸套件',
            '傳動鏈條': '傳動鏈條'
        },
        cylinderDesc: '高品質汽缸套件，適用於各種摩托車型號',
        chainDesc: '專業傳動鏈條，確保最佳傳動效率',
        clutchDesc: '耐用離合器組件，提供順暢的換檔體驗',
        pistonDesc: '精密活塞套件，確保引擎最佳性能'
    },
    'zh-CN': {
        home: '首页',
        about: '关于我们',
        products: '产品目录',
        contact: '联系我们',
        heroTitle: '专业摩托车零件制造商',
        heroSubtitle: '品质保证 · 价格实惠 · 专业服务',
        productsTitle: '产品目录',
        cylinder: '汽缸',
        chain: '链条',
        clutch: '离合器',
        piston: '活塞',
        aboutTitle: '关于我们',
        aboutContent: '我们是台湾专业的摩托车零件制造商，专注于此领域超过30年。我们持续寻找优秀的合作伙伴，以扩展我们友善、专业、高效的服务。',
        contactTitle: '联系我们',
        companyName: '协皇企业有限公司',
        address: '地址：台中市南屯区黎明路一段533-2号',
        phone: '电话：0930 797 299',
        email: 'Email：bounerchang@gmail.com',
        copyright: '© 2024 协皇企业有限公司. All rights reserved.',
        productCategories: '产品分类',
        searchPlaceholder: '搜索产品...',
        noProducts: '此类别暂无产品',
        noSearchResults: '找不到符合的产品',
        stock: '库存',
        sold: '已售',
        originalPrice: '原价',
        currentPrice: '特价',
        inquiry: '询价',
        specifications: '规格',
        model: '型号',
        currency: 'NT$',
        categoryNames: {
            cylinder: '汽缸系列',
            chain: '链条系列',
            clutch: '离合器系列',
            piston: '活塞系列',
            valve: '气门系列',
            sprocket: '齿轮系列',
            brake: '刹车片系列',
            'oil-seal': '油封系列',
            cable: '线材系列'
        },
        categoryDescriptions: {
            cylinder: '高品质汽缸套件，适用于各种摩托车型号',
            chain: '专业传动链条，确保最佳传动效率',
            clutch: '耐用离合器组件，提供顺畅的换档体验',
            piston: '精密活塞套件，确保引擎最佳性能',
            valve: '高精度气门组件，确保引擎气密性',
            sprocket: '耐磨齿轮，提供稳定的传动效果',
            brake: '高性能刹车片，确保行车安全',
            'oil-seal': '优质油封，防止油料泄漏',
            cable: '耐用线材，确保操控灵敏度'
        },
        inquiryMessage: '即将为您询价产品：',
        productName: '产品名称',
        contactUs: '请联系我们',
        productNames: {
            '汽缸套件': '汽缸套件',
            '傳動鏈條': '传动链条'
        },
        cylinderDesc: '高品质汽缸套件，适用于各种摩托车型号',
        chainDesc: '专业传动链条，确保最佳传动效率',
        clutchDesc: '耐用离合器组件，提供顺畅的换档体验',
        pistonDesc: '精密活塞套件，确保引擎最佳性能'
    },
    'en': {
        home: 'Home',
        about: 'About Us',
        products: 'Products',
        contact: 'Contact',
        heroTitle: 'Professional Motorcycle Parts Manufacturer',
        heroSubtitle: 'Quality Guaranteed · Affordable Price · Professional Service',
        productsTitle: 'Product Catalog',
        cylinder: 'Cylinder',
        chain: 'Chain',
        clutch: 'Clutch',
        piston: 'Piston',
        aboutTitle: 'About Us',
        aboutContent: 'We are the factory of producing motorcycle parts in TAIWAN. We focus in it over than 30 years. And We are keep looking for good partners to extend our friendly, professional, executive service.',
        contactTitle: 'Contact Us',
        companyName: 'Xie Huang Enterprise Co., Ltd.',
        address: 'Address: No. 533-2, Sec. 1, Liming Rd., Nantun Dist., Taichung City 408004, Taiwan',
        phone: 'Phone: 0930 797 299',
        email: 'Email: bounerchang@gmail.com',
        copyright: '© 2024 Xie Huang Enterprise Co., Ltd. All rights reserved.',
        productCategories: 'Product Categories',
        searchPlaceholder: 'Search products...',
        noProducts: 'No products in this category',
        noSearchResults: 'No matching products found',
        stock: 'Stock',
        sold: 'Sold',
        originalPrice: 'Original Price',
        currentPrice: 'Special Price',
        inquiry: 'Inquiry',
        specifications: 'Specifications',
        model: 'Model',
        currency: 'NT$',
        categoryNames: {
            cylinder: 'Cylinder Series',
            chain: 'Chain Series',
            clutch: 'Clutch Series',
            piston: 'Piston Series',
            valve: 'Valve Series',
            sprocket: 'Sprocket Series',
            brake: 'Brake Pad Series',
            'oil-seal': 'Oil Seal Series',
            cable: 'Cable Series'
        },
        categoryDescriptions: {
            cylinder: 'High-quality cylinder kits for various motorcycle models',
            chain: 'Professional transmission chains ensuring optimal power delivery',
            clutch: 'Durable clutch components for smooth shifting experience',
            piston: 'Precision piston kits for optimal engine performance',
            valve: 'High-precision valve components ensuring engine sealing',
            sprocket: 'Wear-resistant sprockets for stable transmission',
            brake: 'High-performance brake pads for safe riding',
            'oil-seal': 'Premium oil seals preventing oil leakage',
            cable: 'Durable cables ensuring responsive control'
        },
        inquiryMessage: 'Product Inquiry:',
        productName: 'Product Name',
        contactUs: 'Contact Us',
        productNames: {
            '汽缸套件': 'Cylinder Kit',
            '傳動鏈條': 'Transmission Chain'
        },
        cylinderDesc: 'High-quality cylinder kits for various motorcycle models',
        chainDesc: 'Professional transmission chains ensuring optimal power delivery',
        clutchDesc: 'Durable clutch components for smooth shifting experience',
        pistonDesc: 'Precision piston kits for optimal engine performance'
    }
}; 